### ISSUE TITLE
跌倒检测交流

### ISSUE THREAD

**Issue by hushunda** [chizhanyuefeng/Fall_Detection_for_RNN#1]
你好，我正在作这方面研究，请问下有好的公开的数据集吗，qq1437213444

**Comment by chizhanyuefeng** [comment]
1.MobiFall＆MobiAct DataSet http://www.bmi.teicrete.gr/index.php/research/mobiact

2.SisFall http://sistemic.udea.edu.co/en/investigacion/proyectos/english-falls/

**Comment by chizhanyuefeng** [comment]
@hushunda 1.MobiFall＆MobiAct DataSet http://www.bmi.teicrete.gr/index.php/research/mobiact

2.SisFall http://sistemic.udea.edu.co/en/investigacion/proyectos/english-falls/

**Comment by chizhanyuefeng** [comment]
@hushunda 有关跌倒检测相关数据集很多，但是都没有统一的标准。比如，设备配置人体部位、传感器使用型号及其量程等等。

**Comment by hushunda** [comment]
谢谢你的帮助
