### ISSUE TITLE
数据集的处理

### ISSUE THREAD

**Issue by liuyecool** [chizhanyuefeng/Fall_Detection_for_RNN#3]
您好，我刚开始学习方面的知识，有幸看到了您的代码，想问你一下那个csv文件在网站中下载不到，想问一下您方便上传一下csv文件，或者简单说一下是如何处理得到csv文件的呢！谢谢啦

**Comment by chizhanyuefeng** [comment]
我使用的<The MobiFall Dataset: Fall Detection and Classification with a Smartphone>这篇论文中的数据.处理csv文件可以使用pandas库来进行处理.

**Comment by chizhanyuefeng** [comment]
这周我把我下载的数据挂出来

**Comment by chizhanyuefeng** [comment]
@liuyecool 数据我放到了百度网盘,https://pan.baidu.com/s/1arZMNPs1GzWrQf4beJFCSQ
