### ISSUE TITLE
Data set not found

### ISSUE THREAD

**Issue by swatinair123** [chizhanyuefeng/Fall_Detection_for_RNN#4]
Hi ,
I am not able to find the data set under this link http://www.bmi.teicrete.gr/index.php/research/mobiact. Please advise from here i can download the link.

Thanks in advance

**Comment by chizhanyuefeng** [comment]
The website has been hung up，I don’t  know why.
Ok,this week I will upload this dataset

**Comment by chizhanyuefeng** [comment]
@swatinair123 I was upload the dataset at https://pan.baidu.com/s/1arZMNPs1GzWrQf4beJFCSQ

**Comment by rohan8660** [comment]
@chizhanyuefeng  Can you please upload it somewhere else? Baidu is not easy to access, creating a Baidu account is redundant.
