### ISSUE TITLE
训练集与测试集的划分？

### ISSUE THREAD

**Issue by lyxlty** [chizhanyuefeng/Fall_Detection_for_RNN#5]
您好！1、请问下训练集与测试集你是怎么划分的？我看你训练集是以50hz采样得到的，那测试集怎么得到，采样的话有可能得到重复的吧 ，还是手动划分？2 训练集是先采样得到后经过卡尔曼滤波的吧？这个和原始数据先经过卡尔曼滤波再采样得到的结果应该是一样的吧？ 谢谢了

**Comment by lyxlty** [comment]
@chizhanyuefeng

**Comment by chizhanyuefeng** [comment]
1.数据集是按照9比1进行的划分。
2.采样和滤波先后顺序对结果影响被不大。

**Comment by lyxlty** [comment]
@chizhanyuefeng 嗯，谢谢您的解答，那这个采样是做实验用的吧，无需关注吧？还是得从原始数据划分训练集和测试集，我理解的对吗

**Comment by lyxlty** [comment]
好像我理解的不对，训练集是以50hz采样得到的，那测试集怎么得到？糊涂了，期待您的解答

**Comment by lyxlty** [comment]
![image](https://user-images.githubusercontent.com/11659778/48540925-55918880-e8f6-11e8-90a2-1e20772c784d.png)
您好！我是先滤波后采样，然后划分数据集，运行train_rnn.py报的如图所示，提示列表分配超出范围了，请问下怎么改，多谢了

**Comment by lyxlty** [comment]
@chizhanyuefeng ，麻烦有空解答一下，应该是data_load.py这函数有问题，但没找出来

**Comment by chizhanyuefeng** [comment]
不要使用data_load_abandon.py,这个方法已经弃用了,请使用data_load.py

**Comment by lyxlty** [comment]
嗯，谢谢你解答，我先前是用的data_load.py ,报的一样的错
![image](https://user-images.githubusercontent.com/11659778/48709796-84cf2f00-ec41-11e8-93b8-a21f4132ea6e.png)，后面才使用的data_load_random.py,和data_load_random.py报的同样一个错

**Comment by lyxlty** [comment]
您好，我train里面只放一个csv文件，是可以训练起来的，如下图所示
![image](https://user-images.githubusercontent.com/11659778/48712866-d11e6d00-ec49-11e8-9176-97c8bd768d01.png)，但放入许多个csv文件，还是报的这个错
![image](https://user-images.githubusercontent.com/11659778/48712935-00cd7500-ec4a-11e8-9cfa-f9172506c235.png)，batch改小一点还是报一样的错

**Comment by lyxlty** [comment]
@chizhanyuefeng 后面我合成一个csv了,报的是这个错，
![image](https://user-images.githubusercontent.com/11659778/48781582-41df8b00-ed17-11e8-9bfb-d50c08eaa9bb.png)
，错误出在这行label[s][j] =1 label是个二维数组，麻烦有时间解答一下，感谢

**Comment by chizhanyuefeng** [comment]
@lyxlty 感谢提供的bug,这周末我会进行修改

**Comment by chizhanyuefeng** [comment]
你放到train目录中的csv文件数据存储格式是什么？我昨天测试了一下，train中存放多个训练csv数据，没有问题。
下面是csv数据存储格式
![fall](https://user-images.githubusercontent.com/31909368/48988997-364ef280-f163-11e8-83b6-1d44bcda9ec2.png)

**Comment by lyxlty** [comment]
你好，我的格式和你的差不多，
![image](https://user-images.githubusercontent.com/11659778/48991184-d9583a00-f16c-11e8-8018-6da69c875daf.png)
![image](https://user-images.githubusercontent.com/11659778/48991192-e6752900-f16c-11e8-9966-489308d81bfe.png)
![image](https://user-images.githubusercontent.com/11659778/48991207-f1c85480-f16c-11e8-8e96-56ae4f55a9cb.png)

**Comment by lyxlty** [comment]
@chizhanyuefeng 你好，放入少量的csv是可以跑起来的，比如1到200个，放多了就不行了，比如放入了大于1000个csv，2900+个csv就报了那个错了，后面在服务器上试过了，不是内存小的原因，这样的话是不是只能分部训练了？

**Comment by chizhanyuefeng** [comment]
哦，是上千的文件呀，这个还没测过，我明天测一下试试

**Comment by lyxlty** [comment]
嗯，谢谢，麻烦有空的时候测试一下，我没有调通

**Comment by chizhanyuefeng** [comment]
很抱歉，我只能周六日来调，平时比较忙，见谅。

**Comment by lyxlty** [comment]
嗯嗯，感谢！

**Comment by chizhanyuefeng** [comment]
我尝试了加载2072个训练文件,没有复现bug.你可以尝试单步调试.
![demo1](https://user-images.githubusercontent.com/31909368/49339283-800b7180-f66a-11e8-9741-d13a40a49eaf.png)

**Comment by lyxlty** [comment]
@chizhanyuefeng 您好，不好意思，是我提取后的数据文件有几个有问题，前几天跑通了，请问下train_rnn.py里面的time_step为什么是150  而 run_rnn.py 的time_step 是 50  ，是采样频率？  train_x.append(self._all_data.iloc[start_pos[i]:start_pos[i] + self._extract_data_size, 0:3].values)
 j = int(self._all_data.iloc[start_pos[i] + s:start_pos[i] + s + 1, 6].values[0])这两行也不太明白，

还有测试集我看您是可视化出来了，但准确率您是怎么评估的，我就加了个if判断    if Label[test_label[i * run_step]] == Label[predict[int(time_step - 1)][0]] : count += 1      后面用accuracy=count/num我用您训练好的的模型在这四个 Forward-lying,Front-knees-lying,Back-sitting-chair,Sideward-lying数据集里准确率才60%,请问下是什么原因导致的
