### ISSUE TITLE
这个是使用了传感器得到的数据来做的吗？

### ISSUE THREAD

**Issue by AndyHon** [chizhanyuefeng/Fall_Detection_for_RNN#8]
你好，请问这个是使用传感器得到的数据吗？这个项目能否直接根据摄像头视觉来判断人是否摔倒？

**Comment by chizhanyuefeng** [comment]
使用的是加速度传感器，不能使用摄像头进行判断。数据集方面，使用的是公开数据集在 2019年8月22日，上午11:29，AndyHon <notifications@github.com> 写道：你好，请问这个是使用传感器得到的数据吗？这个项目能否直接根据摄像头视觉来判断人是否摔倒？—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
